project_id = "chefleads"

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]

[studio]
port = 54323
